export const careerArr = [
  {
    type: "FRONT-END",
    title: "RVN",
    subTitle: "RVN event 이벤트 페이지",
    date: "2021.12.20 ~ 2021.12.22",
    children: "RVN - 이벤트 페이지 (반응형)",
    isModal: false,
    skills: ["HTML5", "SCSS"],
    url: "https://rvnnyc.com/blogs/event/holidaypromotion-2112",
  },
  {
    type: "FRONT-END",
    title: "TH-ROAD",
    subTitle: "디자이너 포트폴리오 ( 개인외주 )",
    date: "2021.12.01 ~ 2021.12.31",
    children: "TH-ROAD - 디자이너의 포트폴리오입니다.",
    isModal: true,
    skills: ["React", "Typescript"],
    url: "",
  },
  {
    type: "FRONT-END",
    title: "K-MAS-2021",
    subTitle: "중소벤처기업부 ( 이벤트 사이트 )",
    date: "2021.11.01 ~ 2021.12.31",
    children:
      "K-MAS 중소벤처기업부에서 진행한 이벤트 프로젝트에서 <br />퍼블리싱 및 Front-end 웹 개발을 전담했습니다.",
    isModal: false,
    skills: ["React", "Typescript", "Google Analytics"],
    url: "https://k-mas.org/",
  },
  {
    type: "FRONT-END, BACK-END",
    title: "화목",
    subTitle: "화목 ( 개인 프로젝트 )",
    date: "2021.08.01 ~ ",
    children:
      "화목 HWAMOEK <br /> Front-end, Back-end 웹, 앱 개발을 전담했습니다.",
    isModal: false,
    skills: ["React", "React-Native", "Prisma", "GraphQL"],
    url: "https://www.hwamoek.io/",
  },
  {
    type: "FRONT-END",
    title: "K-SALE-2021",
    subTitle: "동행세일 ( 이벤트 사이트 )",
    date: "2021.05.22 ~ 2021.07.20",
    children:
      "K-SALE 2021 중소벤처기업부에서 진행한 이벤트 프로젝트에서 <br />퍼블리싱 및 Front-end 웹 개발을 전담했습니다.",
    isModal: false,
    skills: ["React", "Typescript"],
    url: "https://ksale.org/",
  },
  {
    type: "FRONT-END",
    title: "K-MAS-2020",
    subTitle: "중소벤처기업부 ( 이벤트 사이트 )",
    date: "2020.11.01 ~ 2021.12.31",
    children:
      "K-MAS-2020 중소벤처기업부에서 진행한 이벤트 프로젝트에서 <br /> 퍼블리싱을 전담했습니다.",
    isModal: true,
    skills: ["React"],
    url: "",
  },
  {
    type: "FRONT-END",
    title: "orderffrice",
    subTitle: "쇼핑몰 ( 사내 사이드프로젝트 )",
    date: "2020.08.01 ~ 2020.10.30",
    children:
      "orderffrice 사내에서 진행중이던 사이드프로젝트 중 프론트엔드 웹 개발을 전담했습니다.",
    isModal: true,
    skills: ["React"],
    url: "",
  },
  {
    type: "FRONT-END",
    title: "Mutaccato",
    subTitle: "디자이너 포트폴리오 ( 개인외주 )",
    date: "2020.06.01 ~ 2020.07.01",
    children:
      "Mutaccato 반응형 디자이너 포트폴리오입니다. <br /> 웹접근성을 갖춘 HTML 구조와 반응형 CSS, 사용자 인터렉션 위주의 자바스크립트를 담당했습니다. ",
    isModal: false,
    skills: ["HTML5", "CSS3", "Javascript"],
    url: "http://mutaccato.com/",
  },
];
